name: Build and Push Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: us-west2-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Pull latest image for caching
        run: docker pull us-west2-docker.pkg.dev/opennovel-431106/umami/umami:latest || true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: us-west2-docker.pkg.dev/opennovel-431106/umami/umami:latest